### ISSUE TITLE
parent folder

### ISSUE THREAD

**Issue by julienrott** [SpringRoll/grunt-concat-json#1]
Hi,

I have a few json files in the "build" dir I want to concatene into one single json file.
I tried to include arrays, everything seems to work.
But I have the "build" object included. What can I do to not include the "build" parent directory in the final json file ?

Regards

**Comment by bigtimebuddy** [comment]
You can use the base option like this:

``` json
{
        "base": "build",
        "src": "build/**/*.json",
        "dest": "config.json"
}
```

**Comment by julienrott** [comment]
Thank you for your answer, and sorry for opening an issue for this.
Another question if you don't mind : would it be possible to respect the folders hierarchy in the resulting json ?

For example if I have the following hierarchy : 

```
build
 - application.json
 - collections[]
 - - persons.json
 - - rooms.json
```

Is it possible to generate 

```
{
  application: {
    content of application.json
    collections: content of collections[]
  }
}
```

instead of

```
{
  application: {
    content of application.json
  },
  collections: {
    content of collections[]
  }
}
```

**Comment by andrewstart** [comment]
Folders and json with the same names are actually merged, so you could use the folder hierarchy:

```
build
 - application.json
 - application
 - - collections[]
 - - - persons.json
 - - - rooms.json
```

**Comment by julienrott** [comment]
Great thank you very much !

**Comment by rschoenbichler** [comment]
It would be great if you could mention that in the readme.
I think it would be nice to make use of the common "cwd" property instead of the base property.

**Comment by bigtimebuddy** [comment]
@kleinerroemer Thanks for the suggestion. Created a new release (0.0.8) which uses `cwd` instead of `base`. The `base` property is still supported but we'll deprecate in the future. It's documented in the readme.

The example above would be: 

``` json
{
        "cwd": "build",
        "src": "**/*.json",
        "dest": "config.json"
}
```
