### ISSUE TITLE
cwd isn't excluding working directory from concatenated output file.

### ISSUE THREAD

**Issue by silentsilas** [SpringRoll/grunt-concat-json#3]
Here's my grunt task for concat-json:

```
"concat-json": {
    options: {
        space: '\t',
    },
    "casestudy": {
        cwd: '_src/assembly/_data/casestudy/',
        src: '**/*.{json,yml}',
        dest:'_src/assembly/_data/casestudy.json',
    }
},
```

I'm basically wanting to concatenate all the files in the casestudy folder and output it up a level. However, the output .json file still retains the working directory with these settings:

```
{
    "_src": {
        "assembly": {
            "_data": {
                "casestudy": {
                    "some_folder": {
                        "some_key": "some_value" 
                    }
                }
            }
        }
    }
}
```

I only want the final output to contain:

```
"some_folder": {
    "some_key": "some_value"
}
```

Is there something I'm doing wrong? I'm using grunt@4.1.2, npm@2.14.4, and grunt-concat-json@0.0.10.

**Comment by silentsilas** [comment]
It seems all I had to do was take out the trailing slash in cwd! Now it works just as expected.

```
"concat-json": {
    options: {
        space: '\t',
    },
    "casestudy": {
        cwd: '_src/assembly/_data/casestudy',
        src: '**/*.{json,yml}',
        dest:'<%= pkg.buildPath %>assembly/_data/casestudy.json',
    }
},
```

Successfully outputted to my _data folder:

```
{
    "some_folder" : {
        "some_value": "some_key"
    }
}
```

Thanks a million for this plugin. Now I can modularize my often complex assemble.io data files.

**Comment by bigtimebuddy** [comment]
Cool, you're welcome @Poeticode!
